name: Java and typescript package releasing

on:
#  release: # TODO: reset this after stable workflow running
#    types: [published] # TODO: reset this after stable workflow running
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v4
        with:
          node-version: 24 # CHANGE: eredetileg 20 volt
      - run: |
         cd ./js
         npm ci
        shell: bash
      - run: |
          cd ./js
          npm test
        shell: bash

  publish-gpr:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v4
        with:
          node-version: 24 # CHANGE: eredetileg 20 volt
          registry-url: https://npm.pkg.github.com/
      - run: |
          cd ./js
          npm ci
        shell: bash
      - run: |
          cd ./js
          npm publish
        shell: bash
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}